id: P5089E0A8
initial_creation_type: ocr
source_metadata:
  volumes:
    ca9662c2379a410ba0b39727208bb121:
      base_file: v120.txt
      image_group_id: I1PD95965
      title: འཕགས་པ་ཀླུ་སྒྲུབ་ཀྱི་ཞལ་སྔ་ནས་མཛད་པའི་མན་ངག་ཟབ་མོ་བཞུགས།
      total_pages: 1865
      volume_number: 120
